services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.11-alpine
    container_name: quantyx-clickhouse
    restart: unless-stopped
    ports:
      - '8123:8123' # HTTP interface
      - '9000:9000' # Native interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./infrastructure/clickhouse/init:/docker-entrypoint-initdb.d
      - ./infrastructure/clickhouse/config/disable-system-logs.xml:/etc/clickhouse-server/config.d/disable-system-logs.xml
      - ./infrastructure/clickhouse/config/memory.xml:/etc/clickhouse-server/config.d/memory.xml
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ['CMD', 'clickhouse-client', '--query', 'SELECT 1']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:18-trixie
    container_name: quantyx-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: quantyx
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d quantyx']
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:4.1.1
    container_name: quantyx-kafka
    restart: unless-stopped
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Single-node minimal KRaft config
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Retention & compression
      KAFKA_LOG_RETENTION_HOURS: 168 # 7 days
      KAFKA_LOG_RETENTION_BYTES: 1073741824 # 1 GB per partition
      KAFKA_LOG_SEGMENT_BYTES: 104857600 # 100 MB segments
      KAFKA_COMPRESSION_TYPE: producer
      KAFKA_MESSAGE_MAX_BYTES: 5242880 # 5 MB

      # Storage path
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-data:/var/lib/kafka/data

  redis:
    image: redis:8-alpine
    container_name: quantyx-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  kafbat:
    image: kafbat/kafka-ui:latest
    container_name: quantyx-kafbat
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  grafana:
    image: grafana/grafana-oss:latest
    container_name: quantyx-grafana
    restart: unless-stopped
    ports:
      - '3003:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    depends_on:
      - clickhouse

  mailhog:
    image: mailhog/mailhog
    container_name: quantyx-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

volumes:
  clickhouse-data:
  postgres-data:
  kafka-data:
  redis-data:
  grafana-data:

networks:
  default:
    name: quantyx-net
