packages:
  - 'packages/*'
  - 'apps/*'
  - 'libs/shared'
  - 'libs/kafka'
  - 'libs/shared-backend'
  - 'libs/clickhouse'
onlyBuiltDependencies:
  - 'cpu-features'
  - 'esbuild'
  - 'protobufjs'
  - 'ssh2'
  - 'unrs-resolver'
