import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface Country {
  cca3: string;
  region: string;
  subregion: string;
  continents: string[];
}

async function main() {
  const res = await fetch(
    'https://restcountries.com/v3.1/all?fields=cca3,region,subregion,continents'
  );
  if (!res.ok) {
    throw new Error(`Failed to fetch: ${res.status} ${res.statusText}`);
  }

  const data: Country[] = await res.json();

  const iso3Codes = data.map((c) => c.cca3).sort();
  const continents = [
    ...new Set(data.flatMap((c) => c.continents).filter(Boolean)),
  ].sort();
  const regions = [
    ...new Set(data.map((c) => c.subregion || c.region).filter(Boolean)),
  ].sort();

  const output = `// Auto-generated by scripts/generate-country-data.ts — do not edit manually
export const ISO3_CODES = new Set([
${iso3Codes.map((c) => `  '${c}',`).join('\n')}
]) as ReadonlySet<string>;

export const CONTINENTS = [
${continents.map((c) => `  '${c}',`).join('\n')}
] as const;

export const REGIONS = [
${regions.map((r) => `  '${r}',`).join('\n')}
] as const;
`;

  const outPath = join(__dirname, '..', 'src', 'lib', 'country-data.ts');
  writeFileSync(outPath, output, 'utf-8');
  console.log(
    `Wrote ${iso3Codes.length} codes, ${continents.length} continents, ${regions.length} regions → ${outPath}`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
