import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface Country {
  cca2: string;
  cca3: string;
  region: string;
  subregion: string;
  continents: string[];
}

async function main() {
  const res = await fetch(
    'https://restcountries.com/v3.1/all?fields=cca2,cca3,region,subregion,continents',
  );
  if (!res.ok) {
    throw new Error(`Failed to fetch: ${res.status} ${res.statusText}`);
  }

  const data: Country[] = await res.json();

  const iso3Codes = data.map((c) => c.cca3).sort();
  const continents = [
    ...new Set(data.flatMap((c) => c.continents).filter(Boolean)),
  ].sort();
  const regions = [
    ...new Set(data.map((c) => c.subregion || c.region).filter(Boolean)),
  ].sort();

  // Alpha-2 → Alpha-3 mapping
  const a2ToA3 = data
    .filter((c) => c.cca2 && c.cca3)
    .sort((a, b) => a.cca2.localeCompare(b.cca2));

  // Alpha-2 → Continent mapping (use first continent for each country)
  const a2ToContinent = data
    .filter((c) => c.cca2 && c.continents.length > 0)
    .sort((a, b) => a.cca2.localeCompare(b.cca2));

  // Alpha-2 → Region mapping (UN subregion, fallback to region)
  const a2ToRegion = data
    .filter((c) => c.cca2 && (c.subregion || c.region))
    .sort((a, b) => a.cca2.localeCompare(b.cca2));

  const output = `// Auto-generated by scripts/generate-country-data.ts — do not edit manually
export const ISO3_CODES = new Set([
${iso3Codes.map((c) => `  '${c}',`).join('\n')}
]) as ReadonlySet<string>;

export const CONTINENTS = [
${continents.map((c) => `  '${c}',`).join('\n')}
] as const;

export const REGIONS = [
${regions.map((r) => `  '${r}',`).join('\n')}
] as const;

export const COUNTRY_A2_TO_A3: Record<string, string> = {
${a2ToA3.map((c) => `  '${c.cca2}': '${c.cca3}',`).join('\n')}
};

export const COUNTRY_A2_TO_CONTINENT: Record<string, string> = {
${a2ToContinent.map((c) => `  '${c.cca2}': '${c.continents[0]}',`).join('\n')}
};

export const COUNTRY_A2_TO_REGION: Record<string, string> = {
${a2ToRegion.map((c) => `  '${c.cca2}': '${c.subregion || c.region}',`).join('\n')}
};
`;

  const outPath = join(__dirname, '..', 'src', 'lib', 'country-data.ts');
  writeFileSync(outPath, output, 'utf-8');
  console.log(
    `Wrote ${iso3Codes.length} codes, ${continents.length} continents, ${regions.length} regions → ${outPath}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
